version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: todo-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - todo-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/todo_db?schema=public
      NODE_ENV: production
    depends_on:
      - postgres
    networks:
      - todo-network
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma generate &&
        node dist/main"

networks:
  todo-network:
    driver: bridge

volumes:
  postgres-data: 