{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.postgres.service.port }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres.auth.database | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.auth.username | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.auth.password | quote }}
        {{- if .Values.postgres.resources }}
        resources:
          {{- toYaml .Values.postgres.resources | nindent 10 }}
        {{- end }}
{{- end }}
